site_name: Провайдер Zvuk Music для Music Assistant
site_url: https://trudenboy.github.io/ma-provider-zvuk-music/
repo_url: https://github.com/trudenboy/ma-provider-zvuk-music
repo_name: trudenboy/ma-provider-zvuk-music
edit_uri: edit/dev/docs/

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Known Issues: known-issues.md
  - Development:
      - Setup: development.md
      - Docker: dev-docker.md
      - Testing: testing.md
      - Contributing: contributing.md
      - Incident Management: incident-management.md
