#!/usr/bin/env python3
# Auto-generated by ma-provider-tools — do not edit manually.
"""Fail when a class defines a public (or dunder) method below a private one.

Vendored mirror of upstream music-assistant/server
``scripts/check_method_order.py`` (AGENTS.md rule: private methods live at the
bottom of each class), so the rule fails in this repo's pre-commit gate
instead of surfacing only at the first upstream PR
(trudenboy/ma-provider-tools#115). Unlike upstream there is no baseline:
provider trees are small enough to stay clean, so any violation fails.

Usage:
    python scripts/check_method_order.py
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

# ruff: noqa: T201

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "provider"


def find_violations() -> dict[str, list[str]]:
    """Return ``{repo-relative path: [messages]}`` for misplaced methods."""
    violations: dict[str, list[str]] = {}
    for path in sorted(SOURCE_ROOT.rglob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            for lineno, name in _class_violations(node):
                violations.setdefault(rel, []).append(
                    f"{rel}:{lineno}: '{name}' is defined below a private "
                    f"method in class '{node.name}' — move private methods "
                    "to the bottom of the class"
                )
    return violations


def main() -> int:
    """Report every method-order violation; return 1 when any is found."""
    violations = find_violations()
    if not violations:
        return 0
    print(
        "Private methods must live at the bottom of the class "
        "(upstream music-assistant/server AGENTS.md):"
    )
    for path in sorted(violations):
        for message in violations[path]:
            print(f"  {message}")
    return 1


def _class_violations(cls: ast.ClassDef) -> list[tuple[int, str]]:
    """Return ``(lineno, name)`` for each public/dunder method below a private one."""
    bad: list[tuple[int, str]] = []
    seen_private = False
    for child in cls.body:
        if not isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        if _is_private(child.name):
            seen_private = True
        elif seen_private:
            bad.append((child.lineno, child.name))
    return bad


def _is_private(name: str) -> bool:
    """Return whether a method name is private (underscore-prefixed, not dunder)."""
    return name.startswith("_") and not (name.startswith("__") and name.endswith("__"))


if __name__ == "__main__":
    raise SystemExit(main())
