#!/bin/sh
# Init script for Zvuk Music provider Docker dev environment.
# Auto-generated by ma-provider-tools — do not edit manually.
set -e

echo "==> Setting up Zvuk Music provider..."

# Locate MA providers directory inside the container venv
PROVIDERS_DIR=$(/app/venv/bin/python3 -c \
    "import music_assistant.providers, os; print(os.path.dirname(music_assistant.providers.__file__))")

# Remove any existing yandex_music provider (image may bundle one), then symlink ours
rm -rf "${PROVIDERS_DIR}/zvuk_music"
ln -s /tmp/provider "${PROVIDERS_DIR}/zvuk_music"
echo "==> Provider linked: ${PROVIDERS_DIR}/zvuk_music"

# Install provider-specific runtime dependencies (skips music_assistant itself)
DEPS=$(/app/venv/bin/python3 - <<'PYEOF'
import sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
try:
    with open("/tmp/pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    deps = [
        d for d in data.get("project", {}).get("dependencies", [])
        if not d.lower().startswith("music_assistant")
    ]
    print(" ".join(deps))
except Exception:
    pass
PYEOF
)
if [ -n "$DEPS" ]; then
    echo "==> Installing provider dependencies: $DEPS"
    # The official ghcr.io/music-assistant/server image ships uv but no pip
    # in the venv, so the bare `pip install` path crashes on
    # `/app/venv/bin/pip: not found`. Prefer uv when available; fall back
    # to pip for any image that still has it.
    if [ -x /app/venv/bin/uv ]; then
        /app/venv/bin/uv pip install --quiet --python /app/venv/bin/python $DEPS
    else
        /app/venv/bin/pip install --quiet $DEPS
    fi
fi

echo "==> Starting Music Assistant..."
exec /usr/local/bin/entrypoint.sh --data-dir /data --cache-dir /data/.cache
