#!/usr/bin/env bash
# Auto-generated by ma-provider-tools — do not edit manually.
# Dev environment setup for the zvuk_music provider.
set -euo pipefail

# Guard: require uv
if ! command -v uv &>/dev/null; then
  echo "ERROR: uv not found. Install: https://docs.astral.sh/uv/getting-started/installation/"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
env_name="${1:-.venv}"

uv venv "$REPO_ROOT/$env_name"
source "$REPO_ROOT/$env_name/bin/activate"


# Install upstream MA server + provider in editable mode
uv pip install \
  "git+https://github.com/music-assistant/server.git@dev" \
  -e "$REPO_ROOT/.[test]"


# Set up pre-commit hooks if available
if command -v pre-commit &>/dev/null; then
  cd "$REPO_ROOT" && pre-commit install
fi

echo "Setup complete. Activate with: source $env_name/bin/activate"
