#!/usr/bin/env bash
# Auto-generated by ma-provider-tools — do not edit manually.
# Dev environment setup for the zvuk_music provider.
set -euo pipefail

# Guard: require uv
if ! command -v uv &>/dev/null; then
  echo "ERROR: uv not found. Install: https://docs.astral.sh/uv/getting-started/installation/"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
env_name="${1:-.venv}"

uv venv "$REPO_ROOT/$env_name"
source "$REPO_ROOT/$env_name/bin/activate"


# Install upstream MA server + provider in editable mode
MA_SERVER_DIR="${MA_SERVER_DIR:-$HOME/Projects/ma-server}"

if [[ -d "$MA_SERVER_DIR" ]]; then
  echo "Installing ma-server from local clone: $MA_SERVER_DIR"
  # Sync provider source into ma-server before installing
  rsync -a --delete \
    --include="*.py" --include="manifest.json" \
    --exclude="__pycache__/" --exclude="*.pyc" \
    "$REPO_ROOT/provider/" "$MA_SERVER_DIR/music_assistant/providers/zvuk_music/"
  # 1) Install ma-server from local clone (includes test extras + requirements)
  uv pip install -e "$MA_SERVER_DIR/.[test]" -r "$MA_SERVER_DIR/requirements_all.txt"
  # 2) Install our provider's test extras only (no-deps avoids reinstalling ma-server from git)
  uv pip install -e "$REPO_ROOT/.[test]" --no-deps
  # 3) Remove any stale music_assistant namespace packages from site-packages
  #    (editable install uses finder; leftover site-packages shadow the editable path)
  SITE_PKG=$(python -c "import sysconfig; print(sysconfig.get_path('platlib'))")
  rm -rf "$SITE_PKG/music_assistant"
else
  echo "Local ma-server not found, installing from git (may be stale)"
  uv pip install \
    "git+https://github.com/music-assistant/server.git@dev" \
    -e "$REPO_ROOT/.[test]"
fi


# Set up pre-commit hooks if available
if command -v pre-commit &>/dev/null; then
  cd "$REPO_ROOT" && pre-commit install
fi

echo "Setup complete. Activate with: source $env_name/bin/activate"
