name: Test Minimal
on:
  workflow_dispatch:
jobs:
  test:
    uses: trudenboy/ma-provider-tools/.github/workflows/reusable-test.yml@main
    with:
      provider_type: music_provider
      provider_domain: zvuk_music
      provider_path: provider/
      manifest_path: provider/manifest.json
